print(".........................................")
print("tugas: Sisop kelas-B")
print(".........................................")
print("Nama: Dwinggrit Oktaviani") 
print("NPM: 21083010012")
print(".........................................")
print("NOTES:")
print(".........................................")
print("Halo Dunia!")
print("Ini adalah skrip Bash pertamaku di linux!")
